name: Build Docs

on:
  push:
    # this list of paths could potentially impact doc generation.
    paths:
      - '**/typedoc.json'
      - '**/tsconfig*.json'
      - '**/package*.json'
      - '**/*mkdocs*.ya?ml'
      - 'packages/docutils/requirements.txt'
      - 'packages/*/README.md'
      - 'packages/*/docs/**'
      - 'packages/*/**/*.ts'
      - 'packages/*/**/*.js'
      - '.github/workflows/docs.yml' # this file
      - '!**/test/**'
      - '!**/sample-code/**'

  pull_request:
    paths:
      - '**/typedoc.json'
      - '**/tsconfig*.json'
      - '**/package*.json'
      - '**/*mkdocs*.ya?ml'
      - 'packages/docutils/requirements.txt'
      - 'packages/*/README.md'
      - 'packages/*/docs/**'
      - 'packages/*/**/*.ts'
      - 'packages/*/**/*.js'
      - '.github/workflows/docs.yml' # this file
      - '!**/test/**'
      - '!**/sample-code/**'

    branches: [master]

concurrency: preview-${{ github.ref }}

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - name: Install dependencies (Node.js)
        uses: bahmutov/npm-install@1a235c31658a322a3b024444759650ee6345c26d # tag=v1
        with:
          useRollingCache: true
          install-command: npm ci
      - name: Install dependencies (Python)
        run: pip install -r packages/docutils/requirements.txt
      - name: Configure Git User
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Build Docs
        run: npm run docs:preview
      - name: Deploy Preview
        uses: boneskull/pr-preview-action@b4463cc5d5139a053f7150396f143752ecf86500 # v1
        with:
          source-dir: ./packages/appium/docs/site
          custom-url: 'appium.github.io/appium'
